DROP DATABASE IF EXISTS TodoDBTest;

CREATE DATABASE TodoDBTest;

USE TodoDBTest;

CREATE TABLE Todos(
	Id INT PRIMARY KEY AUTO_INCREMENT,
    `Name` VARCHAR(50) NOT NULL,
    `Description` VARCHAR(255) NULL,
    Start_Date DATE NOT NULL,
    End_Date DATE NULL,
    Finished BOOLEAN NOT NULL DEFAULT 0
);

CREATE TABLE Users(
	Id INT PRIMARY KEY AUTO_INCREMENT,
    Username VARCHAR(100) NOT NULL,
    `Password` VARCHAR(250) NOT NULL,
    Account_Expired BOOLEAN NOT NULL DEFAULT 0,
    Account_Locked BOOLEAN NOT NULL DEFAULT 0,
    Credentials_Expired BOOLEAN NOT NULL DEFAULT 0,
    Enabled BOOLEAN NOT NULL DEFAULT 1
);

CREATE TABLE Roles(
	Id INT PRIMARY KEY AUTO_INCREMENT,
	Authority VARCHAR(50) NULL
);

CREATE TABLE Users_Roles(
	User_Id INT NOT NULL,
    Role_Id INT NOT NULL,
    PRIMARY KEY(User_Id,Role_Id),
	FOREIGN KEY(User_Id) REFERENCES Users(Id),
	FOREIGN KEY(Role_Id) REFERENCES Roles(Id)
);

CREATE TABLE Users_Todos(
	User_Id INT NOT NULL,
    Todo_Id INT NOT NULL,
    PRIMARY KEY(User_Id,Todo_Id),
	FOREIGN KEY(User_Id) REFERENCES Users(Id),
	FOREIGN KEY(Todo_Id) REFERENCES Todos(Id)
);